# =========================
# 1) Build stage (Node LTS recente)
# =========================
FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build  # CRA -> 'build'

# =========================
# 2) Runtime stage (Nginx)
# =========================
FROM nginx:alpine

RUN apk --no-cache update

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
