volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_DATABASE: ${POSTGRES_DB}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./themes:/opt/keycloak/themes:ro
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: image-classifier-frontend:latest
    container_name: image-classifier-frontend
    ports:
      - "3000:80"            
    depends_on:
      - keycloak
    restart: unless-stopped

    volumes:
      - ./keycloak.js:/usr/share/nginx/html/keycloak.js:ro

